### PR TITLE
HID: nintendo: check the return value of alloc_workqueue()

### PR DESCRIPTION
**Pull request by SuperSamus**
Ported from upstream.

### CODE REVIEW

**Comment by nfp0** [comment]
What is this for?

**Comment by SuperSamus** [comment]
From the commit description:
```
The function alloc_workqueue() in nintendo_hid_probe() can fail, but
there is no check of its return value. To fix this bug, its return value
should be checked with new error handling code.

Fixes: https://github.com/torvalds/linux/commit/c4eae84feff3e68c2f385aa10faea4a96791e7ad ("HID: nintendo: add rumble support")
Reported-by: TOTE Robot <oslab@tsinghua.edu.cn>
Signed-off-by: Jia-Ju Bai <baijiaju1990@gmail.com>
Reviewed-by: Silvan Jegen <s.jegen@gmail.com>
Signed-off-by: Jiri Kosina <jkosina@suse.cz>
```

**Comment by nfp0** [comment]
@SuperSamus Thank you, I could not find the original commit.

**Comment by nfp0** [comment]
This is in no way related to the current random disconnection issues, or is it?

**Comment by v1993** [comment]
Yes, it is unrelated. This is just an extra safety check to prevent invalid memory access in case of allocation failure.

Disconnects are an issue with bluetooth stack rather than this module itself from what I know.

**Pull request merged**
