### PR TITLE
added wiimote

### PR DESCRIPTION
**Pull request by KP2048**

### CODE REVIEW

**Comment by nicman23** [comment]
i ll test this but this project is more of a downstream of https://github.com/DanielOgorchock/linux

not sure if i ll add this

**Comment by KP2048** [comment]
Yes. And I copied it over from the upstream. 

It was a separate module also added in that fork.

**Comment by DanielOgorchock** [comment]
The hid-wiimote driver is in the mainline linux kernel

**Comment by nicman23** [comment]
then it should probably be in a different dkms package :)

also per copywrite this should be basically everywhere by now, why add it?

**Comment by KP2048** [comment]
I actually didn’t know it was in the mainline. Oop

**Comment by nicman23** [comment]
:P

**Pull request closed without merging**
